// Reviewed Spanish labels for the calisthenics flow; canonical openGym IDs remain unchanged.
// Partial overlay: uncovered names keep their canonical labels. No legacy catalogue imported.
export default {
  "1326": "Dominadas con agarre supino",
  "1401": "Muscle-up en barra vertical",
  "3286": "Muscle-up con lastre",
  "3295": "Repeticiones de front lever",
  "3296": "Front lever",
  "3298": "Plancha con piernas abiertas",
  "3299": "Plancha completa",
  "3300": "Inclinación de plancha",
  "3301": "Plancha en rana",
  "3302": "Parada de manos",
  "3312": "Muscle-up con lastre en barra",
  "3327": "Flexiones en plancha completa",
  "0017": "Dominadas asistidas en máquina",
  "0652": "Dominadas",
  "0662": "Flexiones",
  "0471": "Flexiones en parada de manos",
  "0558": "Muscle-up con impulso",
  "0631": "Muscle-up",
  "1004": "Sentadilla con banda",
  "1009": "Peso muerto con piernas extendidas y banda",
  "1016": "Flexión de muñeca con banda",
  "1254": "Press de pecho con banda",
  "1344": "Remo inclinado con barra EZ y agarre supino",
  "1350": "Remo sentado en máquina",
  "1373": "Elevación de talones de pie sin carga",
  "1408": "Puente de glúteos con banda",
  "1417": "Curl femoral unilateral diagonal con pelota",
  "1425": "Prensa de piernas unilateral a 45°",
  "1459": "Peso muerto rumano con mancuernas",
  "3645": "Puente unilateral con la otra pierna extendida",
  "0534": "Sentadilla goblet con pesa rusa",
  "0739": "Prensa de piernas a 45°",
  "0043": "Sentadilla profunda con barra",
  "0336": "Zancadas con mancuernas",
  "0085": "Peso muerto rumano con barra",
  "0032": "Peso muerto con barra",
  "0549": "Balanceo con pesa rusa",
  "0586": "Curl femoral acostado en máquina",
  "0599": "Curl femoral sentado en máquina",
  "0696": "Curl femoral inverso autoasistido en el suelo",
  "0795": "Curl femoral de pie a una pierna",
  "0289": "Press de pecho con mancuernas",
  "0577": "Press de pecho en máquina",
  "0025": "Press de pecho con barra",
  "0989": "Press de pecho unilateral con giro y banda",
  "0576": "Press de pecho en máquina",
  "0293": "Remo inclinado con mancuernas",
  "0861": "Remo sentado en polea",
  "0027": "Remo inclinado con barra",
  "0988": "Remo bajo unilateral de pie con banda",
  "0198": "Jalón al pecho en polea",
  "0970": "Dominadas asistidas con banda",
  "0405": "Press de hombros sentado con mancuernas",
  "0603": "Press de hombros en máquina",
  "0426": "Press de hombros de pie con mancuernas",
  "0997": "Press de hombros con banda",
  "0334": "Elevaciones laterales con mancuernas",
  "0285": "Curl de bíceps alternado con mancuernas",
  "0006": "Toques alternados de talones",
  "0001": "Abdominal parcial (3/4)",
  "0003": "Bicicleta abdominal",
  "0154": "Aperturas inversas en polea",
  "0447": "Curl de bíceps con barra EZ",
  "1748": "Extensión de tríceps acostado con barra EZ detrás de la cabeza"
}
